types:
    products:
        type: object
        properties:
            id:
                type: number
                required: false
            name: 
                type: string
                required: true
            price:
                type: number
                required: true
    users:
        type: object
        properties:
            id:
                type: number
                required: false
            username: 
                type: string
                required: true
            pass: 
                type: string
                required: true
            name: 
                type: string
                required: true